import { Trip, Expense, User } from '../types';
import { saveFile } from '../utils/saveFile';

function calculateBalances(
  expenses: Expense[],
  participantIds: string[]
): Record<string, number> {
  const balances: Record<string, number> = {};
  participantIds.forEach((id) => (balances[id] = 0));
  expenses.forEach((exp) => {
    const share = exp.amount / exp.participants.length;
    balances[exp.payerId] = (balances[exp.payerId] || 0) + exp.amount;
    exp.participants.forEach((pId) => {
      balances[pId] = (balances[pId] || 0) - share;
    });
  });
  return balances;
}

function getParticipantName(participants: User[], id: string): string {
  return participants.find((p) => p.id === id)?.name || 'Unknown';
}

export async function generateTripReportPDF(
  trip: Trip,
  expenses: Expense[],
  participants: User[]
): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Page 1: Trip overview
  doc.setFontSize(22);
  doc.setTextColor(15, 118, 110); // teal-700
  doc.text(trip.title, pageWidth / 2, 30, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text(trip.destination, pageWidth / 2, 40, { align: 'center' });

  const start = new Date(trip.startDate);
  const end = new Date(trip.endDate);
  const durationDays = Math.max(
    1,
    Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24)) + 1
  );

  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const details = [
    `Dates: ${trip.startDate} to ${trip.endDate} (${durationDays} days)`,
    `Status: ${trip.status}`,
    `Participants: ${participants.map((p) => p.name).join(', ')}`,
  ];
  details.forEach((line, i) => {
    doc.text(line, 20, 60 + i * 8);
  });

  if (trip.description) {
    doc.setFontSize(10);
    doc.text('Description:', 20, 92);
    const descLines = doc.splitTextToSize(trip.description, pageWidth - 40);
    doc.text(descLines, 20, 100);
  }

  // Page 2: Expense table
  if (expenses.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59);
    doc.text('Expense Details', 20, 20);

    const totalSpent = expenses.reduce((sum, e) => sum + e.amount, 0);
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Total: Rs. ${totalSpent.toLocaleString()}`, 20, 28);

    const tableData = expenses.map((exp) => [
      exp.date,
      exp.description,
      `Rs. ${exp.amount.toLocaleString()}`,
      getParticipantName(participants, exp.payerId),
      String(exp.participants.length),
    ]);

    autoTable(doc, {
      startY: 34,
      head: [['Date', 'Description', 'Amount', 'Paid By', 'Split']],
      body: tableData,
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [13, 148, 136], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
    });

    // Balance summary after the table
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const finalY = ((doc as any).lastAutoTable?.finalY as number) || 150;
    const balances = calculateBalances(expenses, trip.participantIds);

    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text('Balance Summary', 20, finalY + 16);

    const balanceData = participants.map((p) => {
      const bal = balances[p.id] || 0;
      return [
        p.name,
        `${bal >= 0 ? '+' : ''}Rs. ${Math.round(bal).toLocaleString()}`,
        bal >= 0 ? 'Is owed' : 'Owes',
      ];
    });

    autoTable(doc, {
      startY: finalY + 22,
      head: [['Participant', 'Balance', 'Status']],
      body: balanceData,
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [13, 148, 136], textColor: 255 },
    });
  }

  // Footer on last page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by TripShare • ${new Date().toLocaleString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 20,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    );
  }

  const filename = `trip-${trip.title.replace(/\s+/g, '-').toLowerCase()}.pdf`;
  const pdfBlob = doc.output('blob');
  await saveFile(pdfBlob, filename, 'application/pdf', trip.title);
}

export async function exportExpensesCSV(
  trip: Trip,
  expenses: Expense[],
  participants: User[]
): Promise<void> {
  const rows: string[][] = [];

  // Header
  rows.push(['Date', 'Description', 'Amount', 'Payer', 'Participants', 'Split Amount']);

  // Data rows
  expenses.forEach((exp) => {
    const payerName = getParticipantName(participants, exp.payerId);
    const participantNames = exp.participants
      .map((id) => getParticipantName(participants, id))
      .join('; ');
    const splitAmount = (exp.amount / exp.participants.length).toFixed(2);
    rows.push([
      exp.date,
      `"${exp.description}"`,
      String(exp.amount),
      payerName,
      `"${participantNames}"`,
      splitAmount,
    ]);
  });

  // Total row
  const totalSpent = expenses.reduce((sum, e) => sum + e.amount, 0);
  rows.push([]);
  rows.push(['', 'TOTAL', String(totalSpent), '', '', '']);

  // Balance rows
  const balances = calculateBalances(expenses, trip.participantIds);
  rows.push([]);
  rows.push(['', 'BALANCES', '', '', '', '']);
  participants.forEach((p) => {
    const bal = balances[p.id] || 0;
    rows.push(['', p.name, `${bal >= 0 ? '+' : ''}${Math.round(bal)}`, '', '', '']);
  });

  const csv = rows.map((r) => r.join(',')).join('\n');
  const csvFilename = `expenses-${trip.title.replace(/\s+/g, '-').toLowerCase()}.csv`;
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  await saveFile(blob, csvFilename, 'text/csv', 'Trip Expenses');
}
